# Generated by Django 3.2.10 on 2023-06-02 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='keuskupan',
            name='ordered',
            field=models.IntegerField(default=0, help_text='Displaying keuskupan in ordered.', verbose_name='Ordered'),
        ),
        migrations.AddField(
            model_name='lingkungan',
            name='ordered',
            field=models.IntegerField(default=0, help_text='Displaying lingkungan in ordered.', verbose_name='Ordered'),
        ),
        migrations.AddField(
            model_name='paroki',
            name='ordered',
            field=models.IntegerField(default=0, help_text='Displaying paroki in ordered.', verbose_name='Ordered'),
        ),
        migrations.AlterField(
            model_name='wilayah',
            name='ordered',
            field=models.IntegerField(default=0, help_text='Displaying wilayah in ordered.', verbose_name='Ordered'),
        ),
    ]
