# Generated by Django 3.2.10 on 2023-05-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_event_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='wilayah',
            name='ordered',
            field=models.IntegerField(default=0, help_text='Displaying genre in ordered.', verbose_name='Ordered'),
        ),
    ]
