# Generated by Django 3.2.9 on 2022-02-28 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='types',
            field=models.CharField(blank=True, choices=[('001', 'Admin'), ('002', 'Client')], max_length=3, null=True, verbose_name='Type'),
        ),
    ]
