# Generated by Django 3.2.10 on 2023-05-18 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='types',
            field=models.CharField(blank=True, choices=[('001', 'Admin'), ('002', 'Staff'), ('003', 'Guest')], max_length=3, null=True, verbose_name='Type'),
        ),
    ]
