# Generated by Django 3.2.10 on 2023-05-18 20:37

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingTimeEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('group', models.CharField(db_index=True, max_length=100, verbose_name='Name Group')),
                ('group_en_us', models.CharField(db_index=True, max_length=100, null=True, verbose_name='Name Group')),
                ('group_ja', models.CharField(db_index=True, max_length=100, null=True, verbose_name='Name Group')),
                ('group_ar', models.CharField(db_index=True, max_length=100, null=True, verbose_name='Name Group')),
                ('group_ko', models.CharField(db_index=True, max_length=100, null=True, verbose_name='Name Group')),
                ('group_hi', models.CharField(db_index=True, max_length=100, null=True, verbose_name='Name Group')),
                ('group_es', models.CharField(db_index=True, max_length=100, null=True, verbose_name='Name Group')),
                ('pic_group', models.CharField(db_index=True, max_length=255, verbose_name='PIC Group')),
                ('pic_group_en_us', models.CharField(db_index=True, max_length=255, null=True, verbose_name='PIC Group')),
                ('pic_group_ja', models.CharField(db_index=True, max_length=255, null=True, verbose_name='PIC Group')),
                ('pic_group_ar', models.CharField(db_index=True, max_length=255, null=True, verbose_name='PIC Group')),
                ('pic_group_ko', models.CharField(db_index=True, max_length=255, null=True, verbose_name='PIC Group')),
                ('pic_group_hi', models.CharField(db_index=True, max_length=255, null=True, verbose_name='PIC Group')),
                ('pic_group_es', models.CharField(db_index=True, max_length=255, null=True, verbose_name='PIC Group')),
                ('email', models.EmailField(blank=True, max_length=75, null=True, verbose_name='Email')),
                ('email_en_us', models.EmailField(blank=True, max_length=75, null=True, verbose_name='Email')),
                ('email_ja', models.EmailField(blank=True, max_length=75, null=True, verbose_name='Email')),
                ('email_ar', models.EmailField(blank=True, max_length=75, null=True, verbose_name='Email')),
                ('email_ko', models.EmailField(blank=True, max_length=75, null=True, verbose_name='Email')),
                ('email_hi', models.EmailField(blank=True, max_length=75, null=True, verbose_name='Email')),
                ('email_es', models.EmailField(blank=True, max_length=75, null=True, verbose_name='Email')),
                ('mobile', models.CharField(blank=True, max_length=64, null=True, verbose_name='Mobile')),
                ('mobile_en_us', models.CharField(blank=True, max_length=64, null=True, verbose_name='Mobile')),
                ('mobile_ja', models.CharField(blank=True, max_length=64, null=True, verbose_name='Mobile')),
                ('mobile_ar', models.CharField(blank=True, max_length=64, null=True, verbose_name='Mobile')),
                ('mobile_ko', models.CharField(blank=True, max_length=64, null=True, verbose_name='Mobile')),
                ('mobile_hi', models.CharField(blank=True, max_length=64, null=True, verbose_name='Mobile')),
                ('mobile_es', models.CharField(blank=True, max_length=64, null=True, verbose_name='Mobile')),
                ('url_guest_book', models.TextField(blank=True, null=True, verbose_name='Link Guest Book')),
                ('user_update', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ('keuskupan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.keuskupan', verbose_name='Keuskupan')),
                ('lingkungan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.lingkungan', verbose_name='Lingkungan')),
                ('paroki', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.paroki', verbose_name='Paroki')),
                ('time_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.timeevent', verbose_name='Time Event')),
                ('wilayah', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.wilayah', verbose_name='Wilayah')),
            ],
            options={
                'verbose_name': 'BookingTimeEvent',
                'verbose_name_plural': '001001 Booking Time Event',
                'unique_together': {('time_event', 'keuskupan', 'paroki', 'wilayah', 'lingkungan', 'group')},
            },
        ),
        migrations.CreateModel(
            name='GuestBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Name')),
                ('name_en_us', models.CharField(db_index=True, max_length=255, null=True, verbose_name='Name')),
                ('name_ja', models.CharField(db_index=True, max_length=255, null=True, verbose_name='Name')),
                ('name_ar', models.CharField(db_index=True, max_length=255, null=True, verbose_name='Name')),
                ('name_ko', models.CharField(db_index=True, max_length=255, null=True, verbose_name='Name')),
                ('name_hi', models.CharField(db_index=True, max_length=255, null=True, verbose_name='Name')),
                ('name_es', models.CharField(db_index=True, max_length=255, null=True, verbose_name='Name')),
                ('gender', models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female')], max_length=1, null=True, verbose_name='Gender')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('age_en_us', models.IntegerField(null=True, verbose_name='Age')),
                ('age_ja', models.IntegerField(null=True, verbose_name='Age')),
                ('age_ar', models.IntegerField(null=True, verbose_name='Age')),
                ('age_ko', models.IntegerField(null=True, verbose_name='Age')),
                ('age_hi', models.IntegerField(null=True, verbose_name='Age')),
                ('age_es', models.IntegerField(null=True, verbose_name='Age')),
                ('email', models.EmailField(blank=True, max_length=75, null=True, verbose_name='Email')),
                ('email_en_us', models.EmailField(blank=True, max_length=75, null=True, verbose_name='Email')),
                ('email_ja', models.EmailField(blank=True, max_length=75, null=True, verbose_name='Email')),
                ('email_ar', models.EmailField(blank=True, max_length=75, null=True, verbose_name='Email')),
                ('email_ko', models.EmailField(blank=True, max_length=75, null=True, verbose_name='Email')),
                ('email_hi', models.EmailField(blank=True, max_length=75, null=True, verbose_name='Email')),
                ('email_es', models.EmailField(blank=True, max_length=75, null=True, verbose_name='Email')),
                ('mobile', models.CharField(blank=True, max_length=64, null=True, verbose_name='Mobile')),
                ('mobile_en_us', models.CharField(blank=True, max_length=64, null=True, verbose_name='Mobile')),
                ('mobile_ja', models.CharField(blank=True, max_length=64, null=True, verbose_name='Mobile')),
                ('mobile_ar', models.CharField(blank=True, max_length=64, null=True, verbose_name='Mobile')),
                ('mobile_ko', models.CharField(blank=True, max_length=64, null=True, verbose_name='Mobile')),
                ('mobile_hi', models.CharField(blank=True, max_length=64, null=True, verbose_name='Mobile')),
                ('mobile_es', models.CharField(blank=True, max_length=64, null=True, verbose_name='Mobile')),
                ('user_update', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ('booking_time_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.bookingtimeevent', verbose_name='Booking Time Event')),
                ('keuskupan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.keuskupan', verbose_name='Keuskupan')),
                ('lingkungan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.lingkungan', verbose_name='Lingkungan')),
                ('paroki', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.paroki', verbose_name='Paroki')),
                ('wilayah', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.wilayah', verbose_name='Wilayah')),
            ],
            options={
                'verbose_name': 'GuestBook',
                'verbose_name_plural': '002001 Guest Book',
                'unique_together': {('booking_time_event', 'keuskupan', 'paroki', 'wilayah', 'lingkungan', 'name')},
            },
        ),
    ]
