# Generated by Django 3.2.10 on 2022-06-10 23:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BiostarRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id_biostar', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Biostar Group ID ID')),
                ('is_active', models.BooleanField(default=False)),
                ('user_update', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ('biostar_entry_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.biostarentrydevice', verbose_name='Biostar Entry Device')),
                ('biostar_group_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.biostargroupid', verbose_name='Biostar Group ID')),
                ('biostar_relay_output', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.biostarrelayoutput', verbose_name='Biostar Relay Output')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.room', verbose_name='Room')),
            ],
            options={
                'verbose_name': 'BiostarRoom',
                'verbose_name_plural': '003001 Biostar Room',
                'unique_together': {('room', 'biostar_group_id', 'biostar_entry_device', 'biostar_relay_output')},
            },
        ),
        migrations.CreateModel(
            name='BookingRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('local_start_time', models.DateTimeField(blank=True, null=True)),
                ('local_end_time', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('noted', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('noted_en_us', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('noted_ja', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('noted_ar', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('noted_ko', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('noted_hi', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('noted_es', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('user_update', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ('biostar_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.biostarroom', verbose_name='Biostar Room')),
            ],
            options={
                'verbose_name': 'BookingRoom',
                'verbose_name_plural': '003002 Booking Room',
                'unique_together': {('biostar_room', 'start_time', 'end_time')},
            },
        ),
        migrations.CreateModel(
            name='UserBookingRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('is_accessed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('001', 'Waiting access'), ('002', 'Granted access'), ('003', 'Removed access'), ('004', 'Verified card')], default='001', max_length=3)),
                ('status_time', models.DateTimeField(blank=True, null=True)),
                ('local_status_time', models.DateTimeField(blank=True, null=True)),
                ('user_update', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ('booking_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.bookingroom', verbose_name='Booking Room')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'UserBookingRoom',
                'verbose_name_plural': '003003 User Booking Room',
                'unique_together': {('users', 'booking_room')},
            },
        ),
    ]
