# Generated by Django 3.2.10 on 2023-06-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestbook',
            name='paid_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guestbook',
            name='user_paid',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True),
        ),
    ]
