# Generated by Django 3.2.10 on 2023-05-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_alter_guestbook_time_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestbook',
            name='nik',
            field=models.PositiveIntegerField(db_index=True, help_text='KTP/Nomor HP', verbose_name='No Identitas'),
        ),
    ]
