# Generated by Django 3.2.10 on 2023-05-27 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0004_alter_guestbook_nik'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestbook',
            name='attended',
            field=models.BooleanField(default=False),
        ),
    ]
